[theme]
base="light"
primaryColor="#e60000"         # Merah Telkom
backgroundColor="#ffffff"      # Putih bersih
secondaryBackgroundColor="#f9f9f9"  # Abu-abu sangat muda biar kontras
textColor="#000000"            # Hitam
font="sans serif"

[client]
showSidebarNavigation = false