[theme]
base="light"
primaryColor="#FF727C"       
backgroundColor="#ffffff"      
secondaryBackgroundColor="#e5e5e5"  
textColor="#000814"        
font="sans serif"

[client]
showSidebarNavigation = false